//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgeManager.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no open tournament!.
        /// </summary>
        public static string _tournament_not_loaded {
            get {
                return ResourceManager.GetString("_tournament_not_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to database:.
        /// </summary>
        public static string bridgemate_database_error {
            get {
                return ResourceManager.GetString("bridgemate_database_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve results.
        /// </summary>
        public static string bridgemate_retrieve_results {
            get {
                return ResourceManager.GetString("bridgemate_retrieve_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incosistent data: .
        /// </summary>
        public static string bridgemate_retrieve_results_inconsistent_db {
            get {
                return ResourceManager.GetString("bridgemate_retrieve_results_inconsistent_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more pairs in the database than in the tournament. Do you want to add pairs to make up the diference?.
        /// </summary>
        public static string bridgemate_retrieve_results_query_incosistent_pairs {
            get {
                return ResourceManager.GetString("bridgemate_retrieve_results_query_incosistent_pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more sections in the database than in the tournament. Do you want to add sections to make up the diference?.
        /// </summary>
        public static string bridgemate_retrieve_results_query_incosistent_sections {
            get {
                return ResourceManager.GetString("bridgemate_retrieve_results_query_incosistent_sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results retrieved sucessfully!.
        /// </summary>
        public static string bridgemate_retrieve_results_success {
            get {
                return ResourceManager.GetString("bridgemate_retrieve_results_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send data to database, there are no results!.
        /// </summary>
        public static string bridgemate_send_data_no_data {
            get {
                return ResourceManager.GetString("bridgemate_send_data_no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database successfully updated!.
        /// </summary>
        public static string bridgemate_send_data_success {
            get {
                return ResourceManager.GetString("bridgemate_send_data_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data to BWS.
        /// </summary>
        public static string bridgemate_send_data_to_bws {
            get {
                return ResourceManager.GetString("bridgemate_send_data_to_bws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start BCS.
        /// </summary>
        public static string bridgemate_start_BCS {
            get {
                return ResourceManager.GetString("bridgemate_start_BCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start BCS! Error: .
        /// </summary>
        public static string bridgemate_start_BCS_error {
            get {
                return ResourceManager.GetString("bridgemate_start_BCS_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BridgeMate.
        /// </summary>
        public static string bridgemate_title {
            get {
                return ResourceManager.GetString("bridgemate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string exports_title {
            get {
                return ResourceManager.GetString("exports_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a movement.
        /// </summary>
        public static string movements_add_movement {
            get {
                return ResourceManager.GetString("movements-add_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the movement file, exception:.
        /// </summary>
        public static string movements_add_movement_error {
            get {
                return ResourceManager.GetString("movements_add_movement_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove movement.
        /// </summary>
        public static string movements_remove_movement {
            get {
                return ResourceManager.GetString("movements-remove_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string movements_table_description {
            get {
                return ResourceManager.GetString("movements-table-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string movements_table_name {
            get {
                return ResourceManager.GetString("movements-table-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string movements_table_rounds {
            get {
                return ResourceManager.GetString("movements-table-rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string movements_table_tables {
            get {
                return ResourceManager.GetString("movements-table-tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        public static string movements_title {
            get {
                return ResourceManager.GetString("movements-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove pair - no pair is selected!.
        /// </summary>
        public static string player_remove_pair_no_pair_selected {
            get {
                return ResourceManager.GetString("player_remove_pair_no_pair_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove player - no player is selected!.
        /// </summary>
        public static string player_remove_player_no_player_selected {
            get {
                return ResourceManager.GetString("player_remove_player_no_player_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove player - player is in a pair!.
        /// </summary>
        public static string player_remove_player_player_in_pair {
            get {
                return ResourceManager.GetString("player_remove_player_player_in_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a pair.
        /// </summary>
        public static string players_add_pair {
            get {
                return ResourceManager.GetString("players-add_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a pausing pair.
        /// </summary>
        public static string players_add_pause_pair {
            get {
                return ResourceManager.GetString("players_add_pause_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a player.
        /// </summary>
        public static string players_add_player {
            get {
                return ResourceManager.GetString("players-add_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string players_default_name {
            get {
                return ResourceManager.GetString("players_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove pair.
        /// </summary>
        public static string players_remove_pair {
            get {
                return ResourceManager.GetString("players-remove-pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove player.
        /// </summary>
        public static string players_remove_player {
            get {
                return ResourceManager.GetString("players-remove_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string players_table_name {
            get {
                return ResourceManager.GetString("players-table-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string players_table_pairs_id {
            get {
                return ResourceManager.GetString("players-table_pairs-id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1.
        /// </summary>
        public static string players_table_pairs_player_1 {
            get {
                return ResourceManager.GetString("players-table_pairs-player_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2.
        /// </summary>
        public static string players_table_pairs_player_2 {
            get {
                return ResourceManager.GetString("players-table_pairs-player_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string players_table_players_id {
            get {
                return ResourceManager.GetString("players-table_players-id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string players_title {
            get {
                return ResourceManager.GetString("players-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string results_table_board {
            get {
                return ResourceManager.GetString("results-table-board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string results_table_contract {
            get {
                return ResourceManager.GetString("results-table-contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarer.
        /// </summary>
        public static string results_table_declarer {
            get {
                return ResourceManager.GetString("results-table-declarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erased.
        /// </summary>
        public static string results_table_erased {
            get {
                return ResourceManager.GetString("results-table-erased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string results_table_lead {
            get {
                return ResourceManager.GetString("results-table-lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string results_table_notes {
            get {
                return ResourceManager.GetString("results-table-notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair EW.
        /// </summary>
        public static string results_table_pairEW {
            get {
                return ResourceManager.GetString("results-table-pairEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair NS.
        /// </summary>
        public static string results_table_pairNS {
            get {
                return ResourceManager.GetString("results-table-pairNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string results_table_result {
            get {
                return ResourceManager.GetString("results-table-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string results_table_round {
            get {
                return ResourceManager.GetString("results-table-round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string results_table_section {
            get {
                return ResourceManager.GetString("results-table-section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string results_table_table {
            get {
                return ResourceManager.GetString("results-table-table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results_title {
            get {
                return ResourceManager.GetString("results-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create scores.
        /// </summary>
        public static string scoring_create_scores {
            get {
                return ResourceManager.GetString("scoring-create_scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create scores, error:.
        /// </summary>
        public static string scoring_create_scores_error {
            get {
                return ResourceManager.GetString("scoring_create_scores_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate results.
        /// </summary>
        public static string scoring_intermediate_results {
            get {
                return ResourceManager.GetString("scoring_intermediate_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session results.
        /// </summary>
        public static string scoring_session_results {
            get {
                return ResourceManager.GetString("scoring_session_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string scoring_table_maximum_points {
            get {
                return ResourceManager.GetString("scoring-table-maximum_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string scoring_table_opponent {
            get {
                return ResourceManager.GetString("scoring-table-opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string scoring_table_percentage {
            get {
                return ResourceManager.GetString("scoring_table_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string scoring_table_player {
            get {
                return ResourceManager.GetString("scoring-table-player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string scoring_table_points {
            get {
                return ResourceManager.GetString("scoring-table-points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string scoring_table_result {
            get {
                return ResourceManager.GetString("scoring_table_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string scoring_title {
            get {
                return ResourceManager.GetString("scoring-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a section.
        /// </summary>
        public static string sections_add_section {
            get {
                return ResourceManager.GetString("sections_add_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign movement.
        /// </summary>
        public static string sections_assign_movement {
            get {
                return ResourceManager.GetString("sections_assign_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign movement  - no section is selected..
        /// </summary>
        public static string sections_assign_movement_no_section_selected {
            get {
                return ResourceManager.GetString("sections_assign_movement_no_section_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove section.
        /// </summary>
        public static string sections_remove_section {
            get {
                return ResourceManager.GetString("sections_remove_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove section..
        /// </summary>
        public static string sections_remove_section_couldnt_remove {
            get {
                return ResourceManager.GetString("sections_remove_section_couldnt_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove section - no section is selected..
        /// </summary>
        public static string sections_remove_section_no_section_selected {
            get {
                return ResourceManager.GetString("sections_remove_section_no_section_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string sections_table_movement {
            get {
                return ResourceManager.GetString("sections-table-movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string sections_table_name {
            get {
                return ResourceManager.GetString("sections-table-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string sections_table_number {
            get {
                return ResourceManager.GetString("sections-table-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string sections_table_tables {
            get {
                return ResourceManager.GetString("sections-table-tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string sections_title {
            get {
                return ResourceManager.GetString("sections-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a session.
        /// </summary>
        public static string sessions_add_session {
            get {
                return ResourceManager.GetString("sessions_add_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign databse file.
        /// </summary>
        public static string sessions_assign_database {
            get {
                return ResourceManager.GetString("sessions_assign_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove session.
        /// </summary>
        public static string sessions_remove_session {
            get {
                return ResourceManager.GetString("sessions_remove_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove loaded session!.
        /// </summary>
        public static string sessions_remove_sesssion_cannot_remove_loaded {
            get {
                return ResourceManager.GetString("sessions_remove_sesssion_cannot_remove_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file.
        /// </summary>
        public static string sessions_table_database_file {
            get {
                return ResourceManager.GetString("sessions_table_database_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string sessions_table_name {
            get {
                return ResourceManager.GetString("sessions-table-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string sessions_table_number {
            get {
                return ResourceManager.GetString("sessions-table-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string sessions_table_sections {
            get {
                return ResourceManager.GetString("sessions-table-sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string sessions_title {
            get {
                return ResourceManager.GetString("sessions-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string tournament_new {
            get {
                return ResourceManager.GetString("tournament_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string tournament_open {
            get {
                return ResourceManager.GetString("tournament-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string tournament_save {
            get {
                return ResourceManager.GetString("tournament-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string tournament_save_as {
            get {
                return ResourceManager.GetString("tournament-save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string tournament_title {
            get {
                return ResourceManager.GetString("tournament-title", resourceCulture);
            }
        }
    }
}
